---
# tasks file for neovim

- name: ensure neovim is installed
  package:
    name: neovim
    state: latest
  become: true

- name: ensure config directory exists
  file:
    path: $HOME/.config/nvim
    state: directory
    #owner: "{{ ansible_remote_user }}"
    #group: "{{ ansible_remote_user }}"
    mode: 0755

- name: copy neovim config files
  copy:
    src: "{{ item }}"
    dest: "$HOME/.config/nvim/{{ item }}"
    #owner: "{{ ansible_remote_user }}"
    #group: "{{ ansible_remote_user }}"
    mode: 0755
  loop:
    - init.vim
    - nvim-tree.vim
    - pluginsv4.vim
    - pluginsv5.vim
